### ISSUE TITLE
JSON-LD context incorrectly maps odrl:uid to @id

### ISSUE THREAD

**Issue by matthieubosquet** [w3c/odrl#30]
The JSON-LD context "https://www.w3.org/ns/odrl.jsonld" used in all examples (eg. [5](https://www.w3.org/TR/odrl-model/#eg5)) incorrectly maps what one would assume as being the [`odrl:uid` property](https://www.w3.org/TR/odrl-vocab/#term-uid) to JSON-LD's [@id syntax keyword](https://www.w3.org/TR/json-ld11/#syntax-tokens-and-keywords).

<img width="526" alt="Screenshot 2022-11-10 at 19 03 43" src="https://user-images.githubusercontent.com/613619/201183780-9787fd77-fa71-4c61-9071-10df0d4b8684.png">

Which results in the following:
- example json-ld:
    ```json-ld
      {
         "@context": "http://www.w3.org/ns/odrl.jsonld",
         "@type": "Policy",
         "uid": "http://example.org/policy-x"
      }
    ```
- corresponding rdf as turtle:
    ```ttl
    prefix odrl: <http://www.w3.org/ns/odrl/2/>
    
    <http://example.org/policy-x> a odrl:Policy .
    ```
- expected rdf as turtle:
    ```ttl
    prefix odrl: <http://www.w3.org/ns/odrl/2/>
    
    []
        a odrl:Policy ;
        odrl:uid <http://example.org/policy-x> .
    ```

It would be good if the context was ammended to reflect the ODRL vocabulary. I would be happy to submit a [PR](https://github.com/w3c/ns/compare/main...matthieubosquet:ns:patch-1).

See also: https://github.com/w3c/odrl/issues/26

**Comment by vroddon** [comment]
Thanks for the observation Matthieu. Perhaps I have missed your point, because I do not see the context file should behave otherwise.
In the one hand, not having coupled `uid` and `@id` may have as a consequence integrity problems -two identifiers. 
In the other hand, the context file implements the spec:
> "A Policy MUST have one uid property value (of type IRI [[rfc3987](https://www.w3.org/TR/odrl-model/#bib-rfc3987)]) to identify the Policy."
What would be the point of having two different identifiers?
Thanks again for your comment

**Comment by matthieubosquet** [comment]
The ODRL vocabulary defines the [`odrl:uid`](https://www.w3.org/TR/odrl-vocab/#term-uid) property as a way to link instances of Asset, Constraint, LogicalConstraint, Party, Policy and Rule to a unique identifier. 

When using that property, I can write an RDF graph of the form:

```turtle
prefix odrl: <http://www.w3.org/ns/odrl/2/>
prefix ex: <http://example.org/>

[] odrl:uid ex:p1 .
```

Or even make the `odrl:uid` property self-referencing:

```turtle
prefix odrl: <http://www.w3.org/ns/odrl/2/>
prefix ex: <http://example.org/>

ex:p1 odrl:uid ex:p1 .
```

Stating that something has a unique identifier is different from collapsing `uid` as the node identifier.

Going back to the example in my description of the issue, let's consider the following RDF graphs:
1. `[] a odrl:Policy ; odrl:uid ex:p1 .` is made up of two statement: `[]` is an `odrl:Policy` and `[]` has a unique identifier `ex:p1`.
2. `ex:p1 a odrl:Policy` is made up of one statement: `ex:p1` is an `odrl:Policy`.

The first and second RDF graphs are not equivalent, which matters when implementing an ODRL processor.


## Why does it matter?

Let's consider for example a program performing shape validation of ODRL graphs. Such a program would implement checks for every requirement of the ODRL spec, among which: 

> A Policy MUST have one uid property value (of type IRI [[rfc3987](https://www.w3.org/TR/odrl-model/#bib-rfc3987)]) to identify the Policy.
> — https://www.w3.org/TR/odrl-model/#policy

That requirement of the ODRL spec corresponds to verifying that a Policy has exactly one statement of the form `s odrl:uid o`.

If collapsing `uid` as the node identifier, this verification (mandated by the spec), will always fail with error `A Policy MUST have exactly one odrl:uid`.

**Comment by vroddon** [comment]
While it is obvious to me that the two interpretations are different, and that the business is very relevant, I still lean towards my proposal of keeping the current. The only advantage I see with Matthieu's view is that anonymous (in the sense of RDF) policies are possible, which I believe it is against the spirit of the odrl:uid. 

Still, given that I was part of the discussion, I will simply mark this as 'new feature' so that it is considered when a new major change is considered
